<?php 
/**
 * Implements hook_menu().
 */
function media_browser_override_menu() {
  $items['admin/config/media/media-browser-override'] = array(
    'title' => 'Media Browser Override',
    'description' => 'Media Browser Override Configuration Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('media_browser_override_admin_settings_form'),
    'file' => 'includes/media_browser_override.admin.inc',
    'access callback' => 'user_access',
    'access arguments' => array('access administration pages'),
    'theme callback' => 'variable_get',
    'theme arguments' => array('admin_theme'),
    'type' => MENU_NORMAL_ITEM,
    'weight' => 9
  );

  return $items;
}

//The ID of the media wysiwyg form form changed from Media 7.x-2.0-alpha3 to 7.x-2.0-dev

/**
 * Implements hook_form_FORM_ID_alter(). Media 7.x-2.0-alpha3
 */
function media_browser_override_form_media_format_form_alter(&$form, $form_state) {
  media_browser_override_browser_form_alter($form, $form_state);
}

/**
 * Implements hook_form_FORM_ID_alter(). Media 7.x-2.0-dev
 */
function media_browser_override_form_media_wysiwyg_format_form_alter(&$form, $form_state) {
  media_browser_override_browser_form_alter($form, $form_state);
}

/**
 * Helper function that is called by the above form alter hooks
 */
function media_browser_override_browser_form_alter (&$form, $form_state) {
  $default_to_wysiwyg_view_mode = variable_get('media_browser_override_default_wysiwyg_view_mode', 0);
  if(isset($form['options']['format']['#options']['wysiwyg']) && $default_to_wysiwyg_view_mode): 
    $form['options']['format']['#default_value'] = 'wysiwyg';
  endif;

  $skip_view_mode = variable_get('media_browser_override_skip_view_mode_form', 0);
  if($skip_view_mode) :
    $form['#attached']['js'][] = drupal_get_path('module', 'media_browser_override') . '/js/media_browser_override_skip_view_mode_form.js';
  endif;
}

/**
 * Implementation of hook_form_FORM_ID_alter().
 *
 * @todo make this work for any entity, not just nodes 
 * Add the plugin alter js file to any node add / edit forms
 */
function media_browser_override_form_node_form_alter(&$form, $form_state) {
  $alter_plugin_code = variable_get('media_browser_override_alter_plugin_js', 0);

  if($alter_plugin_code) :
    $form['#after_build'][] = 'media_browser_override_node_form_after_build';
  endif;
}

function media_browser_override_node_form_after_build($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'media_browser_override') . '/js/media_browser_override_alter_plugin.js');
  
  return $form;
}